version: '3.8'

services:
  db:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network

  pinger:
    build: ./pinger
    container_name: my-pinger
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
